
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EUXlOakUxTVRBeE1sb1hEVE16TURReU16RTFNVEF4TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTkzCjhwdmJYSlpOQWF1cXJMSkxTYkd0T1ZLb2JmMmhKek5FbTlsUkM4elZDS1hET0hDWnJzU1Jha0Z5S1pEM2tyWDMKbWRJeTNDVk5vMk9ZUmVoTW1IZjBqMXRNV2EzOFRRQzVpdzNUSUYyNXJCZGs0bnVmNUszN3ZYN1c1NmpQc2ZzRAptMncxUGVzZUkrNHB3blV4Snd6WHhpWElreDBQaG9jTGhCN1RLT3VxOWJKQ1pjTkJ3dHBXK1Q3U280UnRnOVY1CmtDK2FVci9ZMVZveTZFMVNXNmhxLzF2c3hCOURteUl0MTlyYkRkc3ZPQlROcCt1S1ZiZE1XVjF3M2RiQXFZSE0KalQ5RTV0WkhuQitTVWNHazJ0eEhuS01VWGNpRVJtMFFwekY2QmZMSUFGZW16b3lwS1NjUGZlcmdVUThvK0xIdQpDUWN6SEswWVVZTy9TNUYwUXlFQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKT1Z6ME1UeWNxK3Jwdk4wTEJCYlhJQzkzNnhNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ0N2NTRqL0dYOHlsNm5YR2czYwo1MVluWnViN2FTV25wVWMvVnovRTJUc1pJc1JwcStvbUdkZGhlNy9UZUhoa1VQTXFIeE1IZmd0K0tsTUFvVUowCm5NZW40am1RVXBmR1FxbTVTSWdNd1BDdUFKRmNvRGpHWTNyQUNXZ3RyUzA3bGRQNG9WdHVTVkZyVjlZeVRKRG4KR0ozT0YyOTdIdVcwZVhBaTNSUFV3WnI5V1AvZndTaEx2cll3Ti9LVkt6WWZ5SEFKSFlHQ3gxM3EvZ21vMUJzaApvN1lNYXlKKzQ0QU02dlVRd2NiRlErdjVVbUtpaFZncE9nY3U3enRZb2JjdXVxQmVIeC8ySHA3WFhOMlBEc29yCnRINTg5UVFEZDEzcUJoR0JldlhWM29lanpseXRYTEhSOUFnUzA5NTYzS0lFaDMxb3hnVWdWajQ0eHhDQWViTUwKSTdFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://8e23c8f8-9a88-4d4d-85d0-3f7c6293bf40.eu-central-1.linodelke.net:443
  name: lke105152

users:
- name: lke105152-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IklkcVdPTVhBcEdwSlNrczg0VEVseEdnRU9peGE0OThkTUs1ZmpFR0ZGREkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tYmtjOTciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYjVkOGZmNzYtMGM2ZS00NzUxLWI3N2EtOTNjMGJlNGIyNzMxIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.Ri3Rnewb6-RMh-buU1hddp46EscfQK93MzJC9I4Sgj53gReGtLz_jdHd9eV2wP9-BV2GC7_wQuBBwISfp9moslqld-kWFCIO4_5ALa1JwUdPqAT7Cxpr9xZqY5gGIoil5MiGEIf_ptUcuX61AfuY6ygGhIDnvaE6aQytg-2_BkLisxhJyQ1dFET3cMyrr4ivGin2kfpmKS9rPAn9W2DWzlf_GioWtHy2IICkU_6othxlqOYoAeTHmYLLDqFQnl9tZFSBWfzWRQ09zVUQ6LEvvR2aJWYYGcj1rW1e-xyxCiaiIcDVcojESM0xo7Wo0ODchbH1rnmYl1CE53ADTRwfUA

contexts:
- context:
    cluster: lke105152
    namespace: default
    user: lke105152-admin
  name: lke105152-ctx

current-context: lke105152-ctx
